# Generated by Django 5.0.2 on 2024-02-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', '-created']},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
